<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Multivariate GLMs: Interaction Effects | stats-jedi.utf8</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Multivariate GLMs: Interaction Effects | stats-jedi.utf8" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Multivariate GLMs: Interaction Effects | stats-jedi.utf8" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Dustin Fife" />


<meta name="date" content="2021-03-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="multivariate-glms-conditioning-effects.html"/>
<link rel="next" href="probability.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">The Order of the Statistical Jedi</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li><a href="intro.html#the-power-of-repetition-and-myummcomplicated-history-with-statistics">The power of repetition (and my…umm…<em>complicated</em> history with statistics)</a></li>
<li class="chapter" data-level="" data-path="intro.html"><a href="intro.html#but-theres-a-better-way"><i class="fa fa-check"></i>But there’s a better way</a></li>
<li class="chapter" data-level="" data-path="intro.html"><a href="intro.html#the-curriculum-hasnt-changed-in-50-years"><i class="fa fa-check"></i>The Curriculum Hasn’t Changed in 50 Years!</a></li>
<li class="chapter" data-level="" data-path="intro.html"><a href="intro.html#the-general-linear-model-approach"><i class="fa fa-check"></i>The General Linear Model Approach</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ethics.html"><a href="ethics.html"><i class="fa fa-check"></i>Ethics</a>
<ul>
<li class="chapter" data-level="" data-path="ethics.html"><a href="ethics.html#history-of-the-replication-crisis"><i class="fa fa-check"></i>History of the Replication Crisis</a>
<ul>
<li class="chapter" data-level="" data-path="ethics.html"><a href="ethics.html#dederick-stapel"><i class="fa fa-check"></i>Dederick Stapel</a></li>
<li class="chapter" data-level="" data-path="ethics.html"><a href="ethics.html#darryl-bem"><i class="fa fa-check"></i>Darryl Bem</a></li>
<li class="chapter" data-level="" data-path="ethics.html"><a href="ethics.html#the-p-hacking-article"><i class="fa fa-check"></i>The “P-Hacking” Article</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ethics.html"><a href="ethics.html#p-hacking"><i class="fa fa-check"></i>P-hacking</a></li>
<li class="chapter" data-level="" data-path="ethics.html"><a href="ethics.html#the-scientific-method-movement"><i class="fa fa-check"></i>The Scientific Method Movement</a></li>
<li class="chapter" data-level="" data-path="ethics.html"><a href="ethics.html#values-versus-ethics"><i class="fa fa-check"></i>Values versus Ethics</a></li>
<li class="chapter" data-level="" data-path="ethics.html"><a href="ethics.html#the-open-science-values"><i class="fa fa-check"></i>The Open Science Values</a>
<ul>
<li class="chapter" data-level="" data-path="ethics.html"><a href="ethics.html#protecting-humanity"><i class="fa fa-check"></i>1. Protecting humanity</a></li>
<li class="chapter" data-level="" data-path="ethics.html"><a href="ethics.html#seek-truth"><i class="fa fa-check"></i>2. Seek truth</a></li>
<li class="chapter" data-level="" data-path="ethics.html"><a href="ethics.html#openness-and-transparency."><i class="fa fa-check"></i>3. Openness and transparency.</a></li>
<li class="chapter" data-level="" data-path="ethics.html"><a href="ethics.html#humility-and-skepticism."><i class="fa fa-check"></i>4. Humility and skepticism.</a></li>
<li class="chapter" data-level="" data-path="ethics.html"><a href="ethics.html#dissemination."><i class="fa fa-check"></i>5. Dissemination.</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ethics.html"><a href="ethics.html#making-change"><i class="fa fa-check"></i>Making Change</a></li>
<li class="chapter" data-level="" data-path="ethics.html"><a href="ethics.html#further-data-analysis-ethics."><i class="fa fa-check"></i>Further data analysis ethics.</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="measurement.html"><a href="measurement.html"><i class="fa fa-check"></i>Measurement</a>
<ul>
<li class="chapter" data-level="" data-path="measurement.html"><a href="measurement.html#why-am-i-talking-about-measurement"><i class="fa fa-check"></i>Why am I talking about measurement?</a></li>
<li class="chapter" data-level="" data-path="measurement.html"><a href="measurement.html#constructs"><i class="fa fa-check"></i>Constructs</a></li>
<li class="chapter" data-level="" data-path="measurement.html"><a href="measurement.html#operational-definitions"><i class="fa fa-check"></i>Operational Definitions</a></li>
<li class="chapter" data-level="" data-path="measurement.html"><a href="measurement.html#validity"><i class="fa fa-check"></i>Validity</a>
<ul>
<li class="chapter" data-level="" data-path="measurement.html"><a href="measurement.html#evaluating-validity"><i class="fa fa-check"></i>Evaluating Validity</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="measurement.html"><a href="measurement.html#reliability"><i class="fa fa-check"></i>Reliability</a>
<ul>
<li class="chapter" data-level="" data-path="measurement.html"><a href="measurement.html#evaluating-reliability"><i class="fa fa-check"></i>Evaluating reliability</a></li>
<li class="chapter" data-level="" data-path="measurement.html"><a href="measurement.html#increasing-reliability"><i class="fa fa-check"></i>Increasing Reliability</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="measurement.html"><a href="measurement.html#variable-types"><i class="fa fa-check"></i>Variable types</a>
<ul>
<li class="chapter" data-level="" data-path="measurement.html"><a href="measurement.html#predictor-versus-outcome-variables"><i class="fa fa-check"></i>Predictor versus Outcome Variables</a></li>
<li class="chapter" data-level="" data-path="measurement.html"><a href="measurement.html#measurement-scales"><i class="fa fa-check"></i>Measurement scales</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="measurement.html"><a href="measurement.html#take-home-message"><i class="fa fa-check"></i>Take-home message</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="univariate-distributions.html"><a href="univariate-distributions.html"><i class="fa fa-check"></i>Univariate Distributions</a>
<ul>
<li class="chapter" data-level="" data-path="univariate-distributions.html"><a href="univariate-distributions.html#categorical-variables"><i class="fa fa-check"></i>Categorical Variables</a>
<ul>
<li class="chapter" data-level="" data-path="univariate-distributions.html"><a href="univariate-distributions.html#column-sorting"><i class="fa fa-check"></i>Column Sorting</a></li>
<li class="chapter" data-level="" data-path="univariate-distributions.html"><a href="univariate-distributions.html#visualizing"><i class="fa fa-check"></i>Visualizing</a></li>
<li class="chapter" data-level="" data-path="univariate-distributions.html"><a href="univariate-distributions.html#interpreting-bar-charts"><i class="fa fa-check"></i>Interpreting Bar Charts</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="univariate-distributions.html"><a href="univariate-distributions.html#numeric-variables"><i class="fa fa-check"></i>Numeric Variables</a>
<ul>
<li class="chapter" data-level="" data-path="univariate-distributions.html"><a href="univariate-distributions.html#what-to-look-out-for"><i class="fa fa-check"></i>What to Look Out For</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="univariate-estimates.html"><a href="univariate-estimates.html"><i class="fa fa-check"></i>Univariate Estimates</a>
<ul>
<li class="chapter" data-level="" data-path="univariate-estimates.html"><a href="univariate-estimates.html#central-tendency-whats-the-most-likely-score"><i class="fa fa-check"></i>Central Tendency: What’s the most likely score?</a>
<ul>
<li class="chapter" data-level="" data-path="univariate-estimates.html"><a href="univariate-estimates.html#mean"><i class="fa fa-check"></i>Mean</a></li>
<li class="chapter" data-level="" data-path="univariate-estimates.html"><a href="univariate-estimates.html#mode"><i class="fa fa-check"></i>Mode</a></li>
<li class="chapter" data-level="" data-path="univariate-estimates.html"><a href="univariate-estimates.html#median"><i class="fa fa-check"></i>Median</a></li>
<li class="chapter" data-level="" data-path="univariate-estimates.html"><a href="univariate-estimates.html#central-tendency-in-jasp"><i class="fa fa-check"></i>Central Tendency in JASP</a></li>
<li class="chapter" data-level="" data-path="univariate-estimates.html"><a href="univariate-estimates.html#central-tendency-in-r"><i class="fa fa-check"></i>Central Tendency in R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="univariate-estimates.html"><a href="univariate-estimates.html#variability-how-precise-are-the-scores"><i class="fa fa-check"></i>Variability: How precise are the scores?</a>
<ul>
<li class="chapter" data-level="" data-path="univariate-estimates.html"><a href="univariate-estimates.html#range"><i class="fa fa-check"></i>Range</a></li>
<li class="chapter" data-level="" data-path="univariate-estimates.html"><a href="univariate-estimates.html#deviations-standard-deviation-and-variance"><i class="fa fa-check"></i>Deviations, Standard Deviation, and Variance</a></li>
<li class="chapter" data-level="" data-path="univariate-estimates.html"><a href="univariate-estimates.html#median-absolute-deviation"><i class="fa fa-check"></i>Median Absolute Deviation</a></li>
<li class="chapter" data-level="" data-path="univariate-estimates.html"><a href="univariate-estimates.html#variability-in-jasp"><i class="fa fa-check"></i>Variability in JASP</a></li>
<li class="chapter" data-level="" data-path="univariate-estimates.html"><a href="univariate-estimates.html#variability-in-r"><i class="fa fa-check"></i>Variability in R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="univariate-estimates.html"><a href="univariate-estimates.html#z-scores-and-probability"><i class="fa fa-check"></i>Z-Scores and Probability</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bivariate-visualizations.html"><a href="bivariate-visualizations.html"><i class="fa fa-check"></i>Bivariate Visualizations</a>
<ul>
<li class="chapter" data-level="" data-path="bivariate-visualizations.html"><a href="bivariate-visualizations.html#avengers-dataset"><i class="fa fa-check"></i>Avengers Dataset</a>
<ul>
<li class="chapter" data-level="" data-path="bivariate-visualizations.html"><a href="bivariate-visualizations.html#visualizing-bivariate-relationships-in-r-using-flexplot"><i class="fa fa-check"></i>Visualizing bivariate relationships in R using Flexplot</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualizations.html"><a href="bivariate-visualizations.html#visualizing-bivariate-relationships-in-jasp-using-visual-modeling"><i class="fa fa-check"></i>Visualizing bivariate relationships in JASP using Visual Modeling</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bivariate-visualizations.html"><a href="bivariate-visualizations.html#scatterplots-numeric-on-numeric"><i class="fa fa-check"></i>Scatterplots: Numeric on numeric</a>
<ul>
<li class="chapter" data-level="" data-path="bivariate-visualizations.html"><a href="bivariate-visualizations.html#what-to-look-for"><i class="fa fa-check"></i>What to look for</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualizations.html"><a href="bivariate-visualizations.html#problems-to-look-out-for"><i class="fa fa-check"></i>Problems to look out for</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualizations.html"><a href="bivariate-visualizations.html#practice-1"><i class="fa fa-check"></i>Practice</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bivariate-visualizations.html"><a href="bivariate-visualizations.html#beeswarm-plots-categorical-on-numeric"><i class="fa fa-check"></i>Beeswarm plots: Categorical on Numeric</a>
<ul>
<li class="chapter" data-level="" data-path="bivariate-visualizations.html"><a href="bivariate-visualizations.html#what-to-look-for-1"><i class="fa fa-check"></i>What to look for</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualizations.html"><a href="bivariate-visualizations.html#problems-to-look-out-for-1"><i class="fa fa-check"></i>Problems to look out for</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bivariate-visualizations.html"><a href="bivariate-visualizations.html#other-bivariate-plots"><i class="fa fa-check"></i>Other Bivariate Plots</a>
<ul>
<li class="chapter" data-level="" data-path="bivariate-visualizations.html"><a href="bivariate-visualizations.html#logistic-plots-numeric-on-binary"><i class="fa fa-check"></i>Logistic Plots: Numeric on Binary</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualizations.html"><a href="bivariate-visualizations.html#association-plots-categorical-on-categorical"><i class="fa fa-check"></i>Association Plots: Categorical on Categorical</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="bivariate-estimates.html"><a href="bivariate-estimates.html"><i class="fa fa-check"></i>Bivariate Estimates</a>
<ul>
<li class="chapter" data-level="" data-path="bivariate-estimates.html"><a href="bivariate-estimates.html#statistics-help-us-predict-things"><i class="fa fa-check"></i>Statistics Help Us Predict Things</a></li>
<li class="chapter" data-level="" data-path="bivariate-estimates.html"><a href="bivariate-estimates.html#conditional-estimates"><i class="fa fa-check"></i>Conditional Estimates</a></li>
<li class="chapter" data-level="" data-path="bivariate-estimates.html"><a href="bivariate-estimates.html#estimates-for-numeric-predictors"><i class="fa fa-check"></i>Estimates for Numeric Predictors</a>
<ul>
<li class="chapter" data-level="" data-path="bivariate-estimates.html"><a href="bivariate-estimates.html#slopes-and-intercepts"><i class="fa fa-check"></i>Slopes and Intercepts</a></li>
<li class="chapter" data-level="" data-path="bivariate-estimates.html"><a href="bivariate-estimates.html#making-predictions"><i class="fa fa-check"></i>Making Predictions</a></li>
<li class="chapter" data-level="" data-path="bivariate-estimates.html"><a href="bivariate-estimates.html#when-slopesintercepts-dont-make-sense"><i class="fa fa-check"></i>When Slopes/Intercepts Don’t Make Sense</a></li>
<li class="chapter" data-level="" data-path="bivariate-estimates.html"><a href="bivariate-estimates.html#correlation-coefficients"><i class="fa fa-check"></i>Correlation Coefficients</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bivariate-estimates.html"><a href="bivariate-estimates.html#estimates-for-categorical-predictors"><i class="fa fa-check"></i>Estimates for Categorical Predictors</a>
<ul>
<li class="chapter" data-level="" data-path="bivariate-estimates.html"><a href="bivariate-estimates.html#slopes-and-intercepts-for-categorical-predictors"><i class="fa fa-check"></i>Slopes and Intercepts for Categorical Predictors?</a></li>
<li><a href="bivariate-estimates.html#cohens-d">Cohen’s <span class="math inline">\(d\)</span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="diagnostics.html"><a href="diagnostics.html"><i class="fa fa-check"></i>Diagnostics</a>
<ul>
<li class="chapter" data-level="" data-path="diagnostics.html"><a href="diagnostics.html#models-are-tools.-and-they-dont-have-feelings."><i class="fa fa-check"></i>Models are tools. And they don’t have feelings.</a></li>
<li class="chapter" data-level="" data-path="diagnostics.html"><a href="diagnostics.html#residuals"><i class="fa fa-check"></i>Residuals</a></li>
<li class="chapter" data-level="" data-path="diagnostics.html"><a href="diagnostics.html#diagnostic-tool-1-histogram-of-the-residuals"><i class="fa fa-check"></i>Diagnostic tool # 1: Histogram of the residuals</a>
<ul>
<li class="chapter" data-level="" data-path="diagnostics.html"><a href="diagnostics.html#sensitivity-analyses"><i class="fa fa-check"></i>Sensitivity Analyses</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="diagnostics.html"><a href="diagnostics.html#diagnostic-tool-2-residual-dependence-rd-plot-for-linearity"><i class="fa fa-check"></i>Diagnostic tool # 2: Residual Dependence (RD) Plot for Linearity</a>
<ul>
<li class="chapter" data-level="" data-path="diagnostics.html"><a href="diagnostics.html#statistical-models-are-lazy"><i class="fa fa-check"></i>Statistical Models are Lazy</a></li>
<li class="chapter" data-level="" data-path="diagnostics.html"><a href="diagnostics.html#residual-dependence-plots"><i class="fa fa-check"></i>Residual Dependence Plots</a></li>
<li class="chapter" data-level="" data-path="diagnostics.html"><a href="diagnostics.html#how-to-fix-nonlinearity"><i class="fa fa-check"></i>How to Fix Nonlinearity</a></li>
<li class="chapter" data-level="" data-path="diagnostics.html"><a href="diagnostics.html#how-to-tell-if-nonlinearity-is-a-problem"><i class="fa fa-check"></i>How to tell if nonlinearity is a problem?</a></li>
<li class="chapter" data-level="" data-path="diagnostics.html"><a href="diagnostics.html#how-much-nonlinearity-is-too-much"><i class="fa fa-check"></i>How much nonlinearity is too much?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="diagnostics.html"><a href="diagnostics.html#diagnostic-tool-3-scale-location-sl-plots-for-homoscedasticity"><i class="fa fa-check"></i>Diagnostic tool # 3: Scale-Location (SL) Plots for Homoscedasticity</a>
<ul>
<li class="chapter" data-level="" data-path="diagnostics.html"><a href="diagnostics.html#spread-location-sl-plots"><i class="fa fa-check"></i>Spread-Location (SL) Plots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="diagnostics.html"><a href="diagnostics.html#outliers-1"><i class="fa fa-check"></i>Outliers</a></li>
<li class="chapter" data-level="" data-path="diagnostics.html"><a href="diagnostics.html#independence"><i class="fa fa-check"></i>Independence</a>
<ul>
<li class="chapter" data-level="" data-path="diagnostics.html"><a href="diagnostics.html#why-do-models-assume-independence"><i class="fa fa-check"></i>Why do models assume independence?</a></li>
<li class="chapter" data-level="" data-path="diagnostics.html"><a href="diagnostics.html#what-happens-if-you-violate-the-independence-assumption"><i class="fa fa-check"></i>What happens if you violate the independence assumption?</a></li>
<li class="chapter" data-level="" data-path="diagnostics.html"><a href="diagnostics.html#how-to-detect-and-handle-dependent-data"><i class="fa fa-check"></i>How to detect and handle dependent data?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="diagnostics.html"><a href="diagnostics.html#summary"><i class="fa fa-check"></i>Summary</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html"><i class="fa fa-check"></i>The General Linear Model</a>
<ul>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#wax-on-wax-off"><i class="fa fa-check"></i>Wax on, wax off</a></li>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#what-is-a-model"><i class="fa fa-check"></i>What is a model</a></li>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#what-is-the-general-linear-model"><i class="fa fa-check"></i>What is the general linear model</a></li>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#what-makes-a-good-statistical-model"><i class="fa fa-check"></i>What makes a good statistical model?</a></li>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#prediction-versus-group-differences"><i class="fa fa-check"></i>Prediction Versus Group Differences</a>
<ul>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#out-with-the-old-in-with-the-shiny"><i class="fa fa-check"></i>Out with the old, in with the shiny</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#one-sample-t-test"><i class="fa fa-check"></i>One-Sample T-Test</a>
<ul>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#traditional-analysis"><i class="fa fa-check"></i>Traditional Analysis</a></li>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#one-sample-t-test-as-a-glm"><i class="fa fa-check"></i>One-Sample T-Test as a GLM</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#independent-sample-t-test"><i class="fa fa-check"></i>Independent Sample T-Test</a>
<ul>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#preparing-data-for-a-t-test"><i class="fa fa-check"></i>Preparing Data for a t-test</a></li>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#traditional-t-test-analysis"><i class="fa fa-check"></i>Traditional t-test Analysis</a></li>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#glm-approach"><i class="fa fa-check"></i>GLM Approach</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#related-t-test"><i class="fa fa-check"></i>Related t-test</a>
<ul>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#traditional-related-t-test-analysis"><i class="fa fa-check"></i>Traditional Related t-test Analysis</a></li>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#glm-analysis-of-a-related-t-test"><i class="fa fa-check"></i>GLM Analysis of a Related t-test</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#anova"><i class="fa fa-check"></i>ANOVA</a>
<ul>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#traditional-analysis-of-anova"><i class="fa fa-check"></i>Traditional Analysis of ANOVA</a></li>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#anova-as-a-glm"><i class="fa fa-check"></i>ANOVA as a GLM</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#regression"><i class="fa fa-check"></i>Regression</a>
<ul>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#traditional-regression-analysis"><i class="fa fa-check"></i>Traditional Regression Analysis</a></li>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#glm-approach-1"><i class="fa fa-check"></i>GLM Approach</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#categorical-outcome-variables"><i class="fa fa-check"></i>Categorical Outcome Variables</a></li>
<li class="chapter" data-level="" data-path="the-general-linear-model.html"><a href="the-general-linear-model.html#its-all-the-same"><i class="fa fa-check"></i>It’s All the Same!</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multivariate-general-linear-models.html"><a href="multivariate-general-linear-models.html"><i class="fa fa-check"></i>Multivariate General Linear Models</a>
<ul>
<li class="chapter" data-level="" data-path="multivariate-general-linear-models.html"><a href="multivariate-general-linear-models.html#what-is-a-multivariate-relationship"><i class="fa fa-check"></i>What is a multivariate relationship?</a></li>
<li class="chapter" data-level="" data-path="multivariate-general-linear-models.html"><a href="multivariate-general-linear-models.html#reasons-to-use-multivariate-glms"><i class="fa fa-check"></i>Reasons to use multivariate GLMs</a></li>
<li class="chapter" data-level="" data-path="multivariate-general-linear-models.html"><a href="multivariate-general-linear-models.html#visualizing-multivariate-relationships-in-flexplot"><i class="fa fa-check"></i>Visualizing Multivariate Relationships in Flexplot</a>
<ul>
<li class="chapter" data-level="" data-path="multivariate-general-linear-models.html"><a href="multivariate-general-linear-models.html#encoding-additional-dimension-using-colorslinessymbols-or-panels"><i class="fa fa-check"></i>Encoding Additional Dimension Using Colors/Lines/Symbols or Panels</a></li>
<li class="chapter" data-level="" data-path="multivariate-general-linear-models.html"><a href="multivariate-general-linear-models.html#encoding-additional-dimensions-using-added-variable-plots"><i class="fa fa-check"></i>Encoding Additional Dimensions Using Added Variable Plots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multivariate-general-linear-models.html"><a href="multivariate-general-linear-models.html#summary-1"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="multivariate-general-linear-models.html"><a href="multivariate-general-linear-models.html#practice-2"><i class="fa fa-check"></i>Practice</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multivariate-glms-conditioning-effects.html"><a href="multivariate-glms-conditioning-effects.html"><i class="fa fa-check"></i>Multivariate GLMs: Conditioning Effects</a>
<ul>
<li class="chapter" data-level="" data-path="multivariate-glms-conditioning-effects.html"><a href="multivariate-glms-conditioning-effects.html#multicollinearity"><i class="fa fa-check"></i>Multicollinearity</a></li>
<li class="chapter" data-level="" data-path="multivariate-glms-conditioning-effects.html"><a href="multivariate-glms-conditioning-effects.html#controlling-by-conditioning"><i class="fa fa-check"></i>Controlling by conditioning</a></li>
<li class="chapter" data-level="" data-path="multivariate-glms-conditioning-effects.html"><a href="multivariate-glms-conditioning-effects.html#conditioning-is-just-residualizing"><i class="fa fa-check"></i>Conditioning is just residualizing</a></li>
<li class="chapter" data-level="" data-path="multivariate-glms-conditioning-effects.html"><a href="multivariate-glms-conditioning-effects.html#all-the-ways-of-thinking-about-conditioning"><i class="fa fa-check"></i>All the ways of thinking about “conditioning”</a></li>
<li class="chapter" data-level="" data-path="multivariate-glms-conditioning-effects.html"><a href="multivariate-glms-conditioning-effects.html#be-careful-about-conditioning-and-using-multiple-regression"><i class="fa fa-check"></i>Be careful about conditioning! (And using multiple regression)</a>
<ul>
<li class="chapter" data-level="" data-path="multivariate-glms-conditioning-effects.html"><a href="multivariate-glms-conditioning-effects.html#conditioning-will-not-prove-causation."><i class="fa fa-check"></i>1. Conditioning will not prove causation.</a></li>
<li class="chapter" data-level="" data-path="multivariate-glms-conditioning-effects.html"><a href="multivariate-glms-conditioning-effects.html#be-careful-what-you-condition-on"><i class="fa fa-check"></i>2. Be Careful what you condition on</a></li>
<li class="chapter" data-level="" data-path="multivariate-glms-conditioning-effects.html"><a href="multivariate-glms-conditioning-effects.html#only-study-and-interpret-the-effects-of-the-interest-variable"><i class="fa fa-check"></i>3. Only study and interpret the effects of the interest variable</a></li>
<li class="chapter" data-level="" data-path="multivariate-glms-conditioning-effects.html"><a href="multivariate-glms-conditioning-effects.html#conditioning-with-interaction-effects."><i class="fa fa-check"></i>4. Conditioning with interaction effects.</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multivariate-glms-conditioning-effects.html"><a href="multivariate-glms-conditioning-effects.html#additional-estimates-of-interest"><i class="fa fa-check"></i>Additional Estimates of Interest</a>
<ul>
<li class="chapter" data-level="" data-path="multivariate-glms-conditioning-effects.html"><a href="multivariate-glms-conditioning-effects.html#slopes"><i class="fa fa-check"></i>Slopes</a></li>
<li class="chapter" data-level="" data-path="multivariate-glms-conditioning-effects.html"><a href="multivariate-glms-conditioning-effects.html#r-squared."><i class="fa fa-check"></i>R squared.</a></li>
<li><a href="multivariate-glms-conditioning-effects.html#semi-partial-r2">Semi-Partial <span class="math inline">\(R^2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multivariate-glms-conditioning-effects.html"><a href="multivariate-glms-conditioning-effects.html#applied-analyses"><i class="fa fa-check"></i>Applied Analyses</a>
<ul>
<li class="chapter" data-level="" data-path="multivariate-glms-conditioning-effects.html"><a href="multivariate-glms-conditioning-effects.html#ancova"><i class="fa fa-check"></i>ANCOVA</a></li>
<li class="chapter" data-level="" data-path="multivariate-glms-conditioning-effects.html"><a href="multivariate-glms-conditioning-effects.html#multiple-regression"><i class="fa fa-check"></i>Multiple Regression</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="multivariate-glms-interaction-effects.html"><a href="multivariate-glms-interaction-effects.html"><i class="fa fa-check"></i>Multivariate GLMs: Interaction Effects</a>
<ul>
<li class="chapter" data-level="" data-path="multivariate-glms-interaction-effects.html"><a href="multivariate-glms-interaction-effects.html#visualizing-interaction-effects"><i class="fa fa-check"></i>Visualizing interaction effects</a>
<ul>
<li class="chapter" data-level="" data-path="multivariate-glms-interaction-effects.html"><a href="multivariate-glms-interaction-effects.html#a-simple-visual-trick-to-tell-if-theres-an-interaction"><i class="fa fa-check"></i>A simple visual trick to tell if there’s an interaction</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multivariate-glms-interaction-effects.html"><a href="multivariate-glms-interaction-effects.html#interactions-between-numeric-variables"><i class="fa fa-check"></i>Interactions between numeric variables</a>
<ul>
<li class="chapter" data-level="" data-path="multivariate-glms-interaction-effects.html"><a href="multivariate-glms-interaction-effects.html#simple-slopes-analysis"><i class="fa fa-check"></i>Simple Slopes Analysis</a></li>
<li class="chapter" data-level="" data-path="multivariate-glms-interaction-effects.html"><a href="multivariate-glms-interaction-effects.html#the-flexplot-approach-to-interpreting-interactions"><i class="fa fa-check"></i>The Flexplot Approach to Interpreting Interactions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multivariate-glms-interaction-effects.html"><a href="multivariate-glms-interaction-effects.html#the-glm-for-interaction-effects"><i class="fa fa-check"></i>The GLM for interaction effects</a></li>
<li class="chapter" data-level="" data-path="multivariate-glms-interaction-effects.html"><a href="multivariate-glms-interaction-effects.html#common-things-people-screw-up-in-the-literature"><i class="fa fa-check"></i>Common things people screw up in the literature</a>
<ul>
<li class="chapter" data-level="" data-path="multivariate-glms-interaction-effects.html"><a href="multivariate-glms-interaction-effects.html#gripe-1.-interpreting-main-effects-when-interactions-exist"><i class="fa fa-check"></i>Gripe #1. Interpreting main effects when interactions exist</a></li>
<li class="chapter" data-level="" data-path="multivariate-glms-interaction-effects.html"><a href="multivariate-glms-interaction-effects.html#gripe-2-failing-to-check-whether-interactions-exist-when-doing-an-ancova"><i class="fa fa-check"></i>Gripe #2: Failing to check whether interactions exist when doing an ANCOVA</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multivariate-glms-interaction-effects.html"><a href="multivariate-glms-interaction-effects.html#estimates-for-interactions"><i class="fa fa-check"></i>Estimates for interactions</a></li>
<li class="chapter" data-level="" data-path="multivariate-glms-interaction-effects.html"><a href="multivariate-glms-interaction-effects.html#applied-analyses-1"><i class="fa fa-check"></i>Applied Analyses</a>
<ul>
<li class="chapter" data-level="" data-path="multivariate-glms-interaction-effects.html"><a href="multivariate-glms-interaction-effects.html#factorial-anova"><i class="fa fa-check"></i>Factorial ANOVA</a></li>
<li class="chapter" data-level="" data-path="multivariate-glms-interaction-effects.html"><a href="multivariate-glms-interaction-effects.html#multiple-regression-1"><i class="fa fa-check"></i>Multiple Regression</a></li>
<li class="chapter" data-level="" data-path="multivariate-glms-interaction-effects.html"><a href="multivariate-glms-interaction-effects.html#mediation-analysis"><i class="fa fa-check"></i>Mediation Analysis</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i>Probability</a>
<ul>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#why-and-when-we-need-probability"><i class="fa fa-check"></i>Why and when we need probability?</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#finite-samples"><i class="fa fa-check"></i>Finite Samples</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#infinite-sets"><i class="fa fa-check"></i>Infinite sets</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#infinite-sets-and-sampling"><i class="fa fa-check"></i>Infinite Sets and Sampling</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#how-to-ensure-a-representative-sample"><i class="fa fa-check"></i>How to ensure a representative sample</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#probability-density-functions"><i class="fa fa-check"></i>Probability Density Functions</a>
<ul>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#computing-probabilities-from-pdfs"><i class="fa fa-check"></i>Computing Probabilities From PDFs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#chapter-summary"><i class="fa fa-check"></i>Chapter Summary</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bayesprobability.html"><a href="bayesprobability.html"><i class="fa fa-check"></i>Probability Two: Bayesian Versus Frequentist Approaches</a>
<ul>
<li class="chapter" data-level="" data-path="bayesprobability.html"><a href="bayesprobability.html#a-tale-of-two-roomates"><i class="fa fa-check"></i>A Tale of Two Roomates</a>
<ul>
<li class="chapter" data-level="" data-path="bayesprobability.html"><a href="bayesprobability.html#toms-approach"><i class="fa fa-check"></i>Tom’s Approach</a></li>
<li class="chapter" data-level="" data-path="bayesprobability.html"><a href="bayesprobability.html#egons-approach"><i class="fa fa-check"></i>Egon’s Approach</a></li>
<li class="chapter" data-level="" data-path="bayesprobability.html"><a href="bayesprobability.html#what-do-they-conclude"><i class="fa fa-check"></i>What do they conclude?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bayesprobability.html"><a href="bayesprobability.html#the-bayesian-approach"><i class="fa fa-check"></i>The Bayesian Approach</a>
<ul>
<li class="chapter" data-level="" data-path="bayesprobability.html"><a href="bayesprobability.html#strengths-of-the-bayesian-approach"><i class="fa fa-check"></i>Strengths of the Bayesian approach</a></li>
<li class="chapter" data-level="" data-path="bayesprobability.html"><a href="bayesprobability.html#weaknessesobjections-to-the-bayesian-approach"><i class="fa fa-check"></i>Weaknesses/Objections to the Bayesian Approach</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bayesprobability.html"><a href="bayesprobability.html#frequentistlikelihood-description"><i class="fa fa-check"></i>Frequentist/Likelihood Description</a>
<ul>
<li class="chapter" data-level="" data-path="bayesprobability.html"><a href="bayesprobability.html#strengths"><i class="fa fa-check"></i>Strengths</a></li>
<li class="chapter" data-level="" data-path="bayesprobability.html"><a href="bayesprobability.html#weaknesses"><i class="fa fa-check"></i>Weaknesses</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="probability-3-the-central-limit-theorem.html"><a href="probability-3-the-central-limit-theorem.html"><i class="fa fa-check"></i>Probability 3: The Central Limit Theorem</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The Order of the Statistical Jedi:
<div style="font-size: .8em;">
Responsibilities, Routines, and Rituals
</div></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multivariate-glms-interaction-effects" class="section level1">
<h1>Multivariate GLMs: Interaction Effects</h1>
<p>It depends.</p>
<p>It depends.</p>
<p>It depends.</p>
<p>Let’s go ahead and make a song out of that, eh?</p>
<p>Iiiiiiiitttttt deeeeeeeeeeeee……peeeeeeeeeeeeeeeeeeeennnnnnnnnnndddddddddddds!</p>
<p>You have a lovely voice, by the way.</p>
<p>Why are we singing this, you ask?</p>
<p>Because we’re talking about interactions. And, as my mom always says, anytime you say the words, ‘it depends,’ you are speaking of an interaction.</p>
<p>Does testosterone increase a person’s sex drive? <em>It depends</em> on gender.</p>
<p>Does eating rotten meat increase the risk of food poisoning? <em>It depends</em> on species. (Vultures don’t get food poisoning from rotten meat!)</p>
<p>Does waking early in the morning increase one’s productivity? <em>It depends</em> on what time you go to bed.</p>
<p>All these are examples of interaction effects.</p>
<p>An interaction occurs when the effect of one variable (e.g., the effect of waking early on productivity) depends on another variable (what time you go to bed).</p>
<p>Let’s think of relationships that do <em>not</em> interact, shall we?</p>
<p>Does a lack of water lead to a higher probability of death? Yes. Across all species, always.</p>
<p>Does learning statistics make one more attractive? Yes. Always.</p>
<div id="visualizing-interaction-effects" class="section level2">
<h2>Visualizing interaction effects</h2>
<p>I’m getting verbose and boring myself with so many words. Let’s look at a graphic, shall we?</p>
<p><img src="stats-jedi_files/figure-html/glmint1-1.png" width="672" /></p>
<div id="a-simple-visual-trick-to-tell-if-theres-an-interaction" class="section level3">
<h3>A simple visual trick to tell if there’s an interaction</h3>
<p>That above plot is right fancy and stuff and illustrates quite nicely an easy-to-use rule to determine whether there’s an interaction effect in the data: <em>if the slopes are not parallel, there is an interaction present in the data</em>.</p>
<p>And, it makes sense. If a slope represents the form of the relationship (e.g., increased rot means more poisoning), and if that slope changes from one group to the next, then it’s clear that the form of the relationship depends on group.</p>
<p>Let’s look at an example where there’s not an interaction:</p>
<p><img src="stats-jedi_files/figure-html/glmintnoint-1.png" width="672" /></p>
<p>Notice the slopes are parallel: it doesn’t matter whether you are male of female, increasing your stats know-how <em>always</em> increases your attractiveness.</p>
<p>ALWAYS!</p>
<p>(How do you think <em>I</em> got to be so attractive!)</p>
<p>By the way, this rule holds, no matter whether you have numeric or categorical variables. But, with categorical variables, sometimes we have to imagine lines pointing from the means.</p>
<p>Let’s look at some examples:</p>
<p><img src="stats-jedi_files/figure-html/glmintcategorical-1.png" width="672" /></p>
<p>In the image above, let’s imagine a line that connects from the means in each group. Are these lines parallel? Absolutely not. This tells us there’s an interaction present. In this case, the relationship between political affiliation and abortion support <em>depends</em> on gender; for males, there’s a very strong difference between liberal and conservatives in their support of abortion. For females, on the other hand, there’s not much of a difference between in abortion support for the two political affiliations.</p>
<p>Let’s look at one more example, but this with all numeric variables.</p>
<p><img src="stats-jedi_files/figure-html/glmintnumeric-1.png" width="672" /></p>
<p>Is there an interaction effect going on here? Absolutely! The lines are not parallel. Not surprisingly, rising earlier means more productivity for those who go to bed early, but rising early for those who go to bed late means <em>less</em> productivity.</p>
</div>
</div>
<div id="interactions-between-numeric-variables" class="section level2">
<h2>Interactions between numeric variables</h2>
<p>In my experience, researchers tend to have an aversion to investigating and interpreting interactions between two numeric variables. Rarely are interactions even mentioned in stats textbooks. When people do try to investigate interactions between numeric variables, they often convert numeric variables into categorical variables prior to analysis in what’s called a “simple slopes analysis.”</p>
<div id="simple-slopes-analysis" class="section level3">
<h3>Simple Slopes Analysis</h3>
<p>Back in the stone ages, people used to do what’s called a “simple slopes analysis.” Alright, so that was a misleading statement. People <em>still</em> do simple slopes analyses. The purpose of a simple slopes analysis is to understand the nature of an interaction.
You (typically) do a simple slopes analysis after you’ve detected a statistically significant interaction. (I almost vomited writing the words <a href="http://https://youtu.be/n4N2GXlkzqI">‘statistically significant’</a>). In other words, interactions are an afterthought, at best.</p>
<p>In my mind, understanding interactions should never be an afterthought.</p>
<p>Let’s look at an example, shall we? Below, is an anova summary table of the avengers dataset:</p>
<caption>
<span id="tab:unnamed-chunk-2">Table 1: </span>
</caption>
<div custom-style="Table Caption">
<em>A Table Illustrating a ‘Statistically Significant’ Interaction Effect.</em>
</div>
<table>
<thead>
<tr class="header">
<th></th>
<th align="left">Df</th>
<th align="left">Sum Sq</th>
<th align="left">Mean Sq</th>
<th align="left">F value</th>
<th align="left">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>speed</td>
<td align="left">1</td>
<td align="left">228,253.076</td>
<td align="left">228,253.076</td>
<td align="left">407.283</td>
<td align="left">0.000</td>
</tr>
<tr class="even">
<td>superpower</td>
<td align="left">1</td>
<td align="left">30,715.327</td>
<td align="left">30,715.327</td>
<td align="left">54.807</td>
<td align="left">0.000</td>
</tr>
<tr class="odd">
<td>speed:superpower</td>
<td align="left">1</td>
<td align="left">18,547.642</td>
<td align="left">18,547.642</td>
<td align="left">33.095</td>
<td align="left">0.000</td>
</tr>
<tr class="even">
<td>Residuals</td>
<td align="left">808</td>
<td align="left">452,826.304</td>
<td align="left">560.429</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
</tbody>
</table>
<p>My oh my, how significant that interaction is.</p>
<p>Once our results tell us something we should have predicted in advance (i.e., an interaction is present), we now want to know the nature of the interaction. What does it look like?</p>
<p>That’s where simple slopes comes in.</p>
<p>A simple slopes analysis simply computes predictions for various levels of the data. So, we might try to see how our model predicts shots.taken (our outcome variable) for a few different values of speed and for each level of superpower (yes versus no). That might look like this (btw, this is a bad way of doing this, so don’t….):</p>
<p><img src="stats-jedi_files/figure-html/mvintsimpleslopes-1.png" width="672" /></p>
<p>So, apparently, speed means more shots taken for non-superheroes and less shots taken for superheroes.</p>
<p>But, this approach to understanding interactions is problematic.</p>
<p>Why?</p>
<p>There’s worse things one could probe an interaction. But, this model takes a continuous variable (speed) and condenses all that rich information into just three values (-1sd, mean, +1sd). It’s not necessary. Instead, why not just plot a regular-old scatterplot (and maybe have different panels for superheroes and non-superheroes)?</p>
<p>By the way, this is <em>exactly</em> what flexplot does: where possible, it maintains the continuous nature of the data. There’s no funky coding we have to do. We don’t have to save predictions to excel then export them to another program. It just does this naturally.</p>
</div>
<div id="the-flexplot-approach-to-interpreting-interactions" class="section level3">
<h3>The Flexplot Approach to Interpreting Interactions</h3>
<p>So a simple slopes is probably not the best way of investigating interactions. If anyone suggests you convert a numeric variable into discrete categories, please hurl your best “yo momma” joke at them. I’d really appreciate it. When you convert a numeric variable to a categorical variable, you are throwing away information and risk introducing bias.</p>
<p>So, don’t do it.</p>
<p>Flexplot makes it super easy to visualize these. It does so by…um…</p>
<p>…categorizing one of the numeric variables and displaying separate plots for each category.</p>
<p>“Wait a minute!” you say. “Didn’t you just say those who categorize variables are heathens?”</p>
<p>Why yes. Yes I did.</p>
<p>“So why is it okay to plot a numeric variable as if it’s a categorical variable, but it’s not okay to categorize a numeric variable from the start?”</p>
<p>Good question!</p>
<p>I’ve got three answers. First, when we categorize a numeric variable <em>for just the plots</em>, it does nothing to the actual numbers. So the slopes, p-values, bayes factors, semi-partial correlations, etc. are unaffected by how I plot them.</p>
<p>Second, as opposed to a simple slopes analysis, we’re <em>not</em> categorizing all continuous variables. Notice in the plot below, we have <em>not</em> converted speed to a categorical variable. Compared to the simple slopes plot, this has a richness of information. We only categorize when we have to, and even then, it’s just for visualization purposes.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="multivariate-glms-interaction-effects.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">flexplot</span>(shots.taken<span class="sc">~</span>speed <span class="sc">+</span> superpower, <span class="at">data=</span>avengers)</span></code></pre></div>
<p><img src="stats-jedi_files/figure-html/glmintintflex-1.png" width="672" /></p>
<p>Third, as I will stress throughout this book, it is very important with multivariate data to view the data in multiple ways. Just about every visualization is going to have to compress information just to make the data viewable. For example, if we’re looking at the relationship between speed, shots taken, and strength, we’re going to have to categorize one variable. In the left image, I’ve categorized speed, while in the right plot I’ve categorized strength. Both plots offer a different perspective on the analysis.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="multivariate-glms-interaction-effects.html#cb2-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">=</span> <span class="fu">flexplot</span>(shots.taken<span class="sc">~</span>strength <span class="sc">|</span> speed, <span class="at">data=</span>avengers)</span>
<span id="cb2-2"><a href="multivariate-glms-interaction-effects.html#cb2-2" aria-hidden="true" tabindex="-1"></a>b <span class="ot">=</span> <span class="fu">flexplot</span>(shots.taken<span class="sc">~</span>speed <span class="sc">|</span> strength, <span class="at">data=</span>avengers)</span>
<span id="cb2-3"><a href="multivariate-glms-interaction-effects.html#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb2-4"><a href="multivariate-glms-interaction-effects.html#cb2-4" aria-hidden="true" tabindex="-1"></a>a<span class="sc">+</span>b</span></code></pre></div>
<p><img src="stats-jedi_files/figure-html/glmintdoublecategoriziation-1.png" width="672" /></p>
<p>So, in short, there’s no reason to fear numeric interactions. Flexplot handles these with aplomb and a-cherry, and provided you view the data from multiple angles, you’ll circumvent any problems with categorizing numeric variables.</p>
</div>
</div>
<div id="the-glm-for-interaction-effects" class="section level2">
<h2>The GLM for interaction effects</h2>
<p>See how clever I am? I <em>started</em> with visuals long before I went to the math. I’d-a lost you if I’d started with the math.</p>
<p>But, now that you’ve warmed up, it’s time to do some math.</p>
<p>How do you express an interaction effect as a GLM? It’s actually quite easy:</p>
<p><span class="math inline">\(y = b_0 + b_1 X_1 + b_2 X_2 + \mathbf{b_3 X_1 \times X_2}\)</span></p>
<p>All we did was add a new variable, called an interaction effect, that is <em>literally</em> the product of the two variables.</p>
<p>Let me show you how that’s done, but <em>not</em> because you’re going to have to do this. <strong>R will do this for you in the background! You don’t have to do this! I’m just showing you for illustrative purposes!</strong></p>
<p>Let’s look at the first few rows of the avengers dataset:</p>
<table>
<thead>
<tr class="header">
<th align="right">iq</th>
<th align="right">agility</th>
<th align="right">speed</th>
<th align="right">agility_speed_interaction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">118</td>
<td align="right">27</td>
<td align="right">5.05</td>
<td align="right">136.35</td>
</tr>
<tr class="even">
<td align="right">109</td>
<td align="right">54</td>
<td align="right">4.98</td>
<td align="right">268.92</td>
</tr>
<tr class="odd">
<td align="right">90</td>
<td align="right">56</td>
<td align="right">4.84</td>
<td align="right">271.04</td>
</tr>
<tr class="even">
<td align="right">114</td>
<td align="right">63</td>
<td align="right">5.24</td>
<td align="right">330.12</td>
</tr>
<tr class="odd">
<td align="right">116</td>
<td align="right">30</td>
<td align="right">5.01</td>
<td align="right">150.30</td>
</tr>
<tr class="even">
<td align="right">137</td>
<td align="right">62</td>
<td align="right">4.79</td>
<td align="right">296.98</td>
</tr>
</tbody>
</table>
<p>Notice that the last column (called <code>agility_speed_interaction</code>) is <em>exactly</em> equal to agility <span class="math inline">\(\times\)</span> speed. So, when you model an interaction, you are literally creating a new variable that is equal to the two predictors multiplied together.</p>
<p>But, once again, R will do this for you so you don’t have to actually do any sort of multiplication.</p>
<p>How do you tell R to model an interaction? Well, there’s actually two ways to do it:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="multivariate-glms-interaction-effects.html#cb3-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># method 1:</span></span>
<span id="cb3-2"><a href="multivariate-glms-interaction-effects.html#cb3-2" aria-hidden="true" tabindex="-1"></a>mod_interaction <span class="ot">=</span> <span class="fu">lm</span>(iq<span class="sc">~</span>agility <span class="sc">+</span> speed <span class="sc">+</span> agility<span class="sc">:</span>speed, <span class="at">data=</span>avengers)</span>
<span id="cb3-3"><a href="multivariate-glms-interaction-effects.html#cb3-3" aria-hidden="true" tabindex="-1"></a>mod_interaction_2 <span class="ot">=</span> <span class="fu">lm</span>(iq<span class="sc">~</span>agility<span class="sc">*</span>speed, <span class="at">data=</span>avengers)</span></code></pre></div>
<p>Both ways are identical in this situation. The second method (<code>agility*speed</code>) is simply a shortcut. The asterisk just tells R to model all main effects and interactions between those variables. So, if we did <code>agility*speed*superpower</code>, it would model all three main effects, all three two-way interactions (agility/speed, agility/superpower, and speed/superpower), and the three-way interaction (agility/speed/superpower).</p>
<p>As before, we can use the phenomenal cosmic power of flexplot to automate the visualization:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="multivariate-glms-interaction-effects.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(mod_interaction, <span class="at">plot=</span><span class="st">&quot;model&quot;</span>)</span></code></pre></div>
<p><img src="stats-jedi_files/figure-html/glmintautomate-1.png" width="672" /></p>
<p>So, what happens for categorical variables? You can’t very well multiply gender by intelligence. Well, remember a few chapters ago how we zero-fied our categorical variables? In that case, the gender variable went from male/female to 0/1. That zero-fied variable is what is multiplied. Let’s see an example of that with the avengers dataset:</p>
<table>
<thead>
<tr class="header">
<th align="right">iq</th>
<th align="right">agility</th>
<th align="left">superpower</th>
<th align="right">superpower_zerofy</th>
<th align="right">agility_superpower_interaction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">101</td>
<td align="right">61</td>
<td align="left">no</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">107</td>
<td align="right">81</td>
<td align="left">no</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">114</td>
<td align="right">64</td>
<td align="left">no</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">116</td>
<td align="right">36</td>
<td align="left">no</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">112</td>
<td align="right">66</td>
<td align="left">no</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">104</td>
<td align="right">70</td>
<td align="left">yes</td>
<td align="right">1</td>
<td align="right">70</td>
</tr>
</tbody>
</table>
<p>Notice how, when we zero-fy a categorical variable, we end up getting a lot of zeros in the interaction variable. More specifically, all non-superheroes now have a score of zero.</p>
<p>Let’s think a bit deeper about that, but using the GLM:</p>
<p>iq = <span class="math inline">\(b_0\)</span> + <span class="math inline">\(b_1\)</span>agility + <span class="math inline">\(b_2\)</span> superpower + <span class="math inline">\(b_3\)</span> agility <span class="math inline">\(\times\)</span> superpower</p>
<p>Now, remember, all non-superheroes get a score of zero. So let’s actually work out the equation for those without superpowers:</p>
<p><span class="math display">\[\begin{align}
\text{iq} &amp;= b_0 + b_1 \text{agility} + b_2 \times 0 + b_3 \text{agility} \times 0 \\
\text{iq} &amp;= b_0 + b_1 \text{agility}
\end{align}\]</span></p>
<p>That zero makes two terms disappear. What does this equation tell us? <span class="math inline">\(b_0\)</span> is the intercept <em>for the non-superheroes</em> and <span class="math inline">\(b_1\)</span> is the slope <em>for the non-superheroes</em>.</p>
<p>Let’s do the same thing, but for the superheroes:</p>
<p><span class="math display">\[\begin{align}
\text{iq} &amp;= b_0 + b_1 \text{agility} + b_2 \times 1 + b_3 \text{agility} \times 1 \\
\text{iq} &amp;= b_0 + b_1 \text{agility} + b_2 + b_3 \text{agility} \\
\text{iq} &amp;= (b_0 + b_2) + (b_1 + b_3) \text{agility}
\end{align}\]</span></p>
<p>What do <span class="math inline">\(b_2\)</span> and <span class="math inline">\(b_3\)</span> tell us? <span class="math inline">\(b_2\)</span> tells us the <em>difference</em> in intercepts between the superheroes and the nonsuperheroes, while <span class="math inline">\(b_3\)</span> tells us the <em>difference</em> in slopes.</p>
<p>Let’s actually run this model in R and study these values:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="multivariate-glms-interaction-effects.html#cb5-1" aria-hidden="true" tabindex="-1"></a>interaction_model <span class="ot">=</span> <span class="fu">lm</span>(iq<span class="sc">~</span>agility <span class="sc">+</span> superpower <span class="sc">+</span> agility<span class="sc">*</span>superpower, <span class="at">data=</span>avengers)</span>
<span id="cb5-2"><a href="multivariate-glms-interaction-effects.html#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(interaction_model)</span></code></pre></div>
<pre><code>#&gt; 
#&gt; Call:
#&gt; lm(formula = iq ~ agility + superpower + agility * superpower, 
#&gt;     data = avengers)
#&gt; 
#&gt; Residuals:
#&gt;      Min       1Q   Median       3Q      Max 
#&gt; -25.0396  -5.0560  -0.1177   5.1352  27.1002 
#&gt; 
#&gt; Coefficients:
#&gt;                         Estimate Std. Error t value Pr(&gt;|t|)    
#&gt; (Intercept)           110.409694   0.998801 110.542   &lt;2e-16 ***
#&gt; agility                -0.008224   0.019262  -0.427    0.670    
#&gt; superpoweryes          -0.977765   6.085208  -0.161    0.872    
#&gt; agility:superpoweryes   0.017401   0.101544   0.171    0.864    
#&gt; ---
#&gt; Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
#&gt; 
#&gt; Residual standard error: 8.028 on 808 degrees of freedom
#&gt; Multiple R-squared:  0.0002367,  Adjusted R-squared:  -0.003475 
#&gt; F-statistic: 0.06376 on 3 and 808 DF,  p-value: 0.979</code></pre>
<p>For this model, 110.41 is the intercept for the non-superheroes, -0.008 is the slope for the non-superheroes, -0.978 is the difference in intercepts between superheroes and non-superheroes, and 0.017 is the difference in slopes between superheroes and non-superheroes. Remember that we can detect interactions by seeing how different the slopes are. If that fourth parameter (<span class="math inline">\(b_4\)</span> or 0.017 in this example) is close to zero, that means there’s no difference between slopes of the two groups (and hence, no interaction effect). Neato.</p>
<p>I know, I know…This is a little on the technical side. I’m not sure it’s critical that you understand exactly what the math is doing in the background. For most occasions, you don’t need to dissect the coefficients to figure out what’s going on with the interaction; that’s what the visuals are for. What’s more important is that you know there’s no hand-waving going on here. The math in the background is making a sensible choice for operationalizing the interaction.</p>
</div>
<div id="common-things-people-screw-up-in-the-literature" class="section level2">
<h2>Common things people screw up in the literature</h2>
<p>Being a statistician is hard, you know? Our blood pressure is always near to boiling because we take personal offense when someone does something statistically egregious. This happens quite a lot when people model interactions. So, with that in mind, let me address common abuses involving interactions.</p>
<div id="gripe-1.-interpreting-main-effects-when-interactions-exist" class="section level3">
<h3>Gripe #1. Interpreting main effects when interactions exist</h3>
<p>It’s quite common in the literature to see researchers make a smacking big deal out of the statistical significance of main effects when there are interactions in the model. Let me be clear. I might even use bold font for this…you leave me no choice:</p>
<p><strong>You should never interpret a main effect when there’s an interaction in the model!</strong></p>
<p>Again, I’m sorry to resort to such tactics, but I’ve had it up to here with this misunderstanding :)</p>
<p>Let’s think about why that is…When you have an interaction in the model, that means the main effects are not consistent. Let’s look at a graph, shall we? I’m reproducing the volture data:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="multivariate-glms-interaction-effects.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">flexplot</span>(poisoned<span class="sc">~</span>rot.degree <span class="sc">|</span> species, <span class="at">data=</span>volture, <span class="at">method=</span><span class="st">&quot;lm&quot;</span>) <span class="sc">+</span></span>
<span id="cb7-2"><a href="multivariate-glms-interaction-effects.html#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x=</span><span class="fu">element_blank</span>(),</span>
<span id="cb7-3"><a href="multivariate-glms-interaction-effects.html#cb7-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.x=</span><span class="fu">element_blank</span>(),</span>
<span id="cb7-4"><a href="multivariate-glms-interaction-effects.html#cb7-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb7-5"><a href="multivariate-glms-interaction-effects.html#cb7-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.y =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="stats-jedi_files/figure-html/glmintmeint-1.png" width="672" /></p>
<p>Now, let me ask you, what is the effect of rot on the probability of being poisoned? Are you struggling to answer the question? I hope so!</p>
<p>Why? Because the effect of rot <em>depends</em> on species.</p>
<p>When interactions are present, neither the interaction <em>nor</em> the main effect should be interpreted in isolation. They <em>must</em> be interpreted within the context of one another.</p>
<p>How do you best do that? Visually, of course! Visuals are the best way of understanding what’s going on in its entirety.</p>
<p>Here’s the take-home message: if there are main effects in your model, they are uninterpretable. You can only interpret them in the context of the interaction.</p>
</div>
<div id="gripe-2-failing-to-check-whether-interactions-exist-when-doing-an-ancova" class="section level3">
<h3>Gripe #2: Failing to check whether interactions exist when doing an ANCOVA</h3>
<p>This second gripe is quite related to the previous gripe. If there is an interaction in a model, we know that any interpretation of main effects is misleading at best. There’s actually a fancy term for this idea:</p>
<p><strong>The assumption of homogeneity of regression.</strong></p>
<p>What does that mean? That means that when we model any sort of multivariate relationship, we assume any variables that interact with one another have been modeled.</p>
<p>Let’s make that a bit more concrete. Let’s say we want to model the association between exercise and depression, after controlling for age, gender, socioeconomic status, and diet. In other words, exercise is our interest variable, and age/gender/ses/diet are our control variables. Most people fit a simple main effects model, like so:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="multivariate-glms-interaction-effects.html#cb8-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">=</span> <span class="fu">lm</span>(depression<span class="sc">~</span>exercise <span class="sc">+</span> age <span class="sc">+</span> gender <span class="sc">+</span> ses <span class="sc">+</span> diet, <span class="at">data=</span>mydata)</span></code></pre></div>
<p>The assumption of homogeneity of regression assumes that <em>none</em> of the control variables interact with the interest variable.</p>
<p>That’s a very strict assumption!</p>
<p>So, before you ever decide to control for variables, you must inspect the visuals (and estimates) to ensure there’s no evidence of interactions.</p>
<p>That also means we ought to be quite careful about what variables we decide to control for since adding more variables only increases the chances we’ll violate the homogeneity of regression assumption.</p>
</div>
</div>
<div id="estimates-for-interactions" class="section level2">
<h2>Estimates for interactions</h2>
<p>I’ve been dreading this section. Why? Okay, remember how I said that you can’t really disentangle the main effects from the interaction? Likewise, you can’t really disentangle the interaction from the main effects. The whole model really ought to be interpreted in context. So, an estimate of the <em>interaction effect</em> is probably going to be misleading.</p>
<p>Let me get a bit more technical for a bit. I promise, I’ll return to “stats for dummies”-level writing in a bit.</p>
<p>Remember how earlier I mentioned a linear model of superheroes? I ended up writing out two equations, one for superheroes and one for non-superheroes:</p>
<p><span class="math display">\[\begin{align}
\text{iq}_\text{non-superhero} &amp;= b_0 + b_1 \text{agility} \\
\text{iq}_\text{superhero} &amp;= (b_0 + b_2) + (b_1 + b_3) \text{agility}
\end{align}\]</span></p>
<p>And, remember I said that <span class="math inline">\(b_3\)</span> represents the <em>difference</em> in slopes for the superheroes versus the non-superheroes. Or, <span class="math inline">\(b_3\)</span> is the effect of the interaction after removing the main effects.</p>
<p>But main effects and interactions can’t really be (psychologically) interpreted independently.</p>
<p>So, it would be nice to have a Cohen’s d-like effect size measure for what is considered small, medium, and large effects sizes for interactions. (And there have been attempts to do this). But, that would be misleading because these really are dependent on the nature of the main effects.</p>
<p>Having said that, flexplot does report the "semi-partial <span class="math inline">\(R^2\)</span>. You can interpret that, but it can be misleading, <a href="http://https://quantpsych.net/some-thoughts-on-interaction-terms-coefficients-semi-partial-correlations-and-standardized-betas-greater-than-one/">as I wrote in a blog post once</a>. Instead, here’s what I recommend:</p>
<ol style="list-style-type: decimal">
<li>Fit a model without the main effects and interaction.</li>
<li>Fit a model with the main effects and interaction.</li>
<li>Compute the difference in <span class="math inline">\(R^2\)</span> and report that.</li>
</ol>
<p>Why do I recommend this? Once again, you can’t disentangle the main effects from the interaction, so you might as well report the variance explained between the main effects and the interaction.</p>
<p>Let’s look at an example. Let’s say we’re modeling the relationship between shots taken, speed, and superpower. First, we’ll fit a model without the main effects or interaction:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="multivariate-glms-interaction-effects.html#cb9-1" aria-hidden="true" tabindex="-1"></a>mod_small <span class="ot">=</span> <span class="fu">lm</span>(shots.taken<span class="sc">~</span><span class="dv">1</span>, <span class="at">data=</span>avengers)</span></code></pre></div>
<p>Next, we’ll model the main effects and interaction:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="multivariate-glms-interaction-effects.html#cb10-1" aria-hidden="true" tabindex="-1"></a>mod_interactions <span class="ot">=</span> <span class="fu">lm</span>(shots.taken<span class="sc">~</span>speed<span class="sc">*</span>superpower, <span class="at">data=</span>avengers)</span></code></pre></div>
<p>Now we can compute the difference in <span class="math inline">\(R^2\)</span> using the <code>model.comparison</code> function. (We’ll talk more about this beautiful function later):</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="multivariate-glms-interaction-effects.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model.comparison</span>(mod_small, mod_interactions)</span></code></pre></div>
<pre><code>#&gt; $statistics
#&gt;                       aic      bic bayes.factor      p  rsq
#&gt; mod_small        7831.392 7840.791 0.000000e+00 &lt;2e-16 0.00
#&gt; mod_interactions 7449.252 7472.750 8.301755e+79        0.38
#&gt; 
#&gt; $predicted_differences
#&gt;     0%    25%    50%    75%   100% 
#&gt;  0.252  5.638 11.529 20.987 74.862</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="multivariate-glms-interaction-effects.html#cb13-1" aria-hidden="true" tabindex="-1"></a>rsq <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">summary</span>(mod_interactions)<span class="sc">$</span>r.squared<span class="sc">*</span><span class="dv">100</span>, <span class="at">digits=</span><span class="dv">2</span>)</span></code></pre></div>
<p>Again, we’ll talk about what all these numbers mean later. But for now, we can see the <span class="math inline">\(R^2\)</span> of the two models and easily compute the difference between them. So, our model explains 38% of the variance.</p>
<p>Of course, you could have just looked at the model’s total <span class="math inline">\(R^2\)</span> using <code>estimates(mod_interactions)</code> and it would have been identical. But let’s say you have a control variable (perhaps, strength). Now the model’s <span class="math inline">\(R^2\)</span> isn’t the same as the difference in the model’s <span class="math inline">\(R^2\)</span> anymore:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="multivariate-glms-interaction-effects.html#cb14-1" aria-hidden="true" tabindex="-1"></a>mod_small_control <span class="ot">=</span> <span class="fu">lm</span>(shots.taken<span class="sc">~</span>strength, <span class="at">data=</span>avengers)</span>
<span id="cb14-2"><a href="multivariate-glms-interaction-effects.html#cb14-2" aria-hidden="true" tabindex="-1"></a>mod_interactions_control <span class="ot">=</span> <span class="fu">lm</span>(shots.taken<span class="sc">~</span>strength <span class="sc">+</span> speed<span class="sc">*</span>superpower, <span class="at">data=</span>avengers)</span>
<span id="cb14-3"><a href="multivariate-glms-interaction-effects.html#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">model.comparison</span>(mod_small_control, mod_interactions_control)</span></code></pre></div>
<pre><code>#&gt; $statistics
#&gt;                              aic      bic bayes.factor      p   rsq
#&gt; mod_small_control        7410.87 7424.968 0.000000e+00 &lt;2e-16 0.406
#&gt; mod_interactions_control 7235.51 7263.707 1.040765e+35        0.525
#&gt; 
#&gt; $predicted_differences
#&gt;     0%    25%    50%    75%   100% 
#&gt;  0.000  3.003  6.815 12.025 48.200</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="multivariate-glms-interaction-effects.html#cb16-1" aria-hidden="true" tabindex="-1"></a>diffr <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">diff</span>(<span class="fu">model.comparison</span>(mod_small_control, mod_interactions_control)<span class="sc">$</span>statistics<span class="sc">$</span>rsq), <span class="at">digits=</span><span class="dv">2</span>)</span></code></pre></div>
<p>Now the effect of the interaction/main effects, after controlling for strength, is 0.12.</p>
</div>
<div id="applied-analyses-1" class="section level2">
<h2>Applied Analyses</h2>
<div id="factorial-anova" class="section level3">
<h3>Factorial ANOVA</h3>
<div id="reporting-results-for-a-factorial-anova" class="section level4">
<h4>Reporting Results for a Factorial ANOVA</h4>
</div>
</div>
<div id="multiple-regression-1" class="section level3">
<h3>Multiple Regression</h3>
<div id="reporting-results-for-a-multiple-regression" class="section level4">
<h4>Reporting Results for a Multiple Regression</h4>
</div>
</div>
<div id="mediation-analysis" class="section level3">
<h3>Mediation Analysis</h3>
<div id="reporting-results-for-a-multiple-regression-1" class="section level4">
<h4>Reporting Results for a Multiple Regression</h4>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="multivariate-glms-conditioning-effects.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="probability.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/12-GLM-Interactions.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["stats-jedi.pdf", "stats-jedi.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
